
[required]
auditor_names = ["matias", "porter"]
project_name = "test_project"
client_name = "test_client"
commit_hash_url = "test_commit_url"
starting_date = "01/01/2023"
miro_board_url = "test_miro_url"
audit_folder_path = "."
program_lib_path = "../star-atlas-programs/sol-programs/scream/programs/crafting/src/lib.rs"
project_repository_url = "git@git.kudelski.com:Matias.Barrios/test_project.git"
[optional]
program_instructions_path = ""
